# .github/workflows/docs.yml
name: "Build & Publish Doxygen Docs"

on:
  push:
    branches:
      - main
  pull_request:

jobs:
  docs:
    runs-on: ubuntu-latest
    steps:
      # 1. Checkout your repo
      - name: Checkout code
        uses: actions/checkout@v4

      # 2. Install Doxygen + Graphviz (optional)
      - name: Install dependencies
        run: |
          sudo apt-get update
          sudo apt-get install -y doxygen graphviz

      # 3. Run Doxygen
      - name: Generate docs
        uses: mattnotmitt/doxygen-action@v1.9.5
        with:
          doxyfile-path: MailLib/Doxyfile
          output: docs/html

      # 4. Deploy to gh-pages
      - name: Publish to GitHub Pages
        uses: peaceiris/actions-gh-pages@v3
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}
          publish_dir: MailLib/docs/html
          publish_branch: gh-pages
